### ISSUE TITLE
issue with service credientials for machine learning

### ISSUE THREAD

**Issue by imokya** [cloud-annotations/training#99] opened 2019-08-01 00:43 UTC
I ran a test last week everthing was fine. this morning I  found the gernerated service credientials for machine learning have no username and password fields any more. machine learning service authentication failed. I think they have changed the auth strategy.

**Comment by jufabeck2202** [comment] 2019-08-01 08:14
I can confirm that. When creating a new service credential.

**Comment by hacker-h** [comment] 2019-08-01 08:42
Same here. This is really frustrating, I can't do anything right now.
Even the exisiting credentials have been invalidated, how is it possible that you get locked out from one day to another without any notice?

**Comment by bourdakos1** [comment] 2019-08-01 12:11
Yea it looks like they changed the token service, I’ll try to push a fix ASAP

**Comment by bourdakos1** [comment] 2019-08-01 15:17
should be fixed with v1.1.5

To log in to **Watson Machine Learning** you now need an `instance_id`, an `api_key` and a `url`

I'll update the tutorial instructions as well, thanks for making me aware of this 😁

**Closed by bourdakos1** 2019-08-01 15:17 UTC

**Comment by jufabeck2202** [comment] 2019-08-01 15:30
Thanks for the fast fix!
